[package]
name = "boidsy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.12.0", features = ["trace"]}
bevy_egui = "0.24.0"
bevy_spatial = "0.7.0"
typenum = "1.17.0"
rand = "0.8.5"